### ISSUE TITLE
[Bug] Theme builder does not work anymore

### ISSUE THREAD

**Issue by zyriab** [axzilla/templui#56]
Hey,

I was poking at the docs while upgrading my project to TailwindCSS v4 and realized the the theme builder does not work anymore.
My guess is that it's related to the recent Tailwind upgrade.

For reference, here's the generated CSS for the color `yellow`:

```css
@layer base {
	:root {
		--background: 0 0% 100%;
		--foreground: 20 14.3% 4.1%;
		--card: 0 0% 100%;
		--card-foreground: 20 14.3% 4.1%;
		--popover: 0 0% 100%;
		--popover-foreground: 20 14.3% 4.1%;
		--primary: 47.9 95.8% 53.1%;
		--primary-foreground: 26 83.3% 14.1%;
		--secondary: 60 4.8% 95.9%;
		--secondary-foreground: 24 9.8% 10%;
		--muted: 60 4.8% 95.9%;
		--muted-foreground: 25 5.3% 44.7%;
		--accent: 60 4.8% 95.9%;
		--accent-foreground: 24 9.8% 10%;
		--destructive: 0 84.2% 60.2%;
		--destructive-foreground: 60 9.1% 97.8%;
		--border: 20 5.9% 90%;
		--input: 20 5.9% 90%;
		--ring: 20 14.3% 4.1%;
		--radius: 0.3rem;
	}
	.dark {
		--background: 20 14.3% 4.1%;
		--foreground: 60 9.1% 97.8%;
		--card: 20 14.3% 4.1%;
		--card-foreground: 60 9.1% 97.8%;
		--popover: 20 14.3% 4.1%;
		--popover-foreground: 60 9.1% 97.8%;
		--primary: 47.9 95.8% 53.1%;
		--primary-foreground: 26 83.3% 14.1%;
		--secondary: 12 6.5% 15.1%;
		--secondary-foreground: 60 9.1% 97.8%;
		--muted: 12 6.5% 15.1%;
		--muted-foreground: 24 5.4% 63.9%;
		--accent: 12 6.5% 15.1%;
		--accent-foreground: 60 9.1% 97.8%;
		--destructive: 0 62.8% 30.6%;
		--destructive-foreground: 60 9.1% 97.8%;
		--border: 12 6.5% 15.1%;
		--input: 12 6.5% 15.1%;
		--ring: 35.5 91.7% 32.9%;
		--radius: 0.3rem;
	}
}
```

https://github.com/user-attachments/assets/7cf53458-545e-4e93-97f7-55363b478696
